# Generated by Django 2.2.1 on 2019-07-17 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.Screen'),
        ),
    ]
