# Generated by Django 2.2.1 on 2019-07-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_auto_20190717_0311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['my_order']},
        ),
        migrations.AddField(
            model_name='track',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
