# Generated by Django 2.2.1 on 2019-07-17 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_auto_20190717_0318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracklist',
            name='title',
        ),
    ]
