# Generated by Django 2.2.1 on 2019-07-17 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_remove_tracklist_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screen',
            options={},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={},
        ),
        migrations.RemoveField(
            model_name='screen',
            name='my_order',
        ),
        migrations.RemoveField(
            model_name='track',
            name='my_order',
        ),
    ]
