# Generated by Django 2.2.1 on 2019-07-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_auto_20190717_0349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('artist', models.CharField(blank=True, max_length=255, null=True, verbose_name='Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('intro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Introduction')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('intro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Introduction')),
            ],
        ),
        migrations.AlterModelOptions(
            name='screen',
            options={'ordering': ['name']},
        ),
    ]
