# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-23 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('my_order', models.PositiveIntegerField(default=0)),
                ('screen', models.CharField(choices=[('home', 'Home'), ('bangla', 'Bangla'), ('discovery', 'Discovery')], default='home', max_length=15)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=15)),
            ],
            options={
                'ordering': ['my_order'],
            },
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['my_order']},
        ),
        migrations.AddField(
            model_name='comment',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
