# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-23 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_auto_20190723_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='relation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.Component'),
        ),
    ]
