# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-25 04:29
from __future__ import unicode_literals

from django.db import migrations
import gfklookupwidget.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0013_remove_comment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='object_id',
            field=gfklookupwidget.fields.GfkLookupField(),
        ),
    ]
